repos:
  - repo: local
    hooks:
      # Prevent committing .rej files from copier
      - id: forbidden-copier-rej-files
        name: forbidden copier rej files
        entry: found Copier update rejection files; review them and remove them
        language: fail
        files: \.rej$

  - repo: builtin
    hooks:
      - id: check-added-large-files
        args: [--maxkb=100000]
      - id: trailing-whitespace
        exclude: (.*\.sh|.*\.d2|.*\.md|.*\.drawio|.*egg-info.*|)$
      - id: check-merge-conflict
        args: [--assume-in-merge]

default_install_hook_types:
  - pre-commit
  - pre-push
  - post-checkout
  - post-merge
  - post-rewrite
default_stages:
  - pre-commit
  - pre-push
