[input]
macroinvertebrate_db = "T:/Wellington/TT Projects/1001181/1001181.4500/WorkingMaterial/Aquatic Monitoring/Aquatic monitoring spreadsheets/260415_MTMA Macroinvertebrate Database.xlsx"
aquatic_monitoring_db = "T:/Wellington/TT Projects/1001181/1001181.4500/WorkingMaterial/Aquatic Monitoring/Aquatic monitoring spreadsheets/260415_MTMA Aquatic Monitoring Database.xlsx"

[output]
data_xlsx = "C:/Users/beka/source/repos/p-100181.4600-mt-messenger-ecology/data.xlsx"
figures_dir = "C:/Users/beka/source/repos/p-100181.4600-mt-messenger-ecology/figures"
tables_dir = "C:/Users/beka/source/repos/p-100181.4600-mt-messenger-ecology/tables"
