name: Static Checks
permissions: {}
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths-ignore:
            - "docs/**"
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "**/*.md"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    analyze:
        name: Run
        runs-on: "ubuntu-latest"
        permissions:
            contents: read # Required to checkout for analysing the code
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Run pre-commit checks
              uses: pre-commit/action@2c7b3805fd2a0fd8c1884d09c769a791cc835b95 # v3.0.1
