name: Tests
permissions: {}
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths-ignore:
            - "docs/**"
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "docs/**"
            - "**/*.md"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    tests:
        name: Run
        runs-on: "ubuntu-latest"
        permissions:
            contents: read # Required to checkout the test suite
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Set up R
              uses: r-lib/actions/setup-r@v2
              with:
                  r-version: "4.5"
                  use-public-rspm: true

            - name: Set up renv
              uses: r-lib/actions/setup-renv@v2

            - name: Run testthat suite
              run: >
                Rscript --vanilla -e "
                  source('renv/activate.R');
                  library(readxl);
                  library(openxlsx);
                  library(dplyr);
                  library(tidyr);
                  library(lubridate);
                  testthat::test_dir('tests/r', stop_on_failure=TRUE)
                "
